
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Lab PC 02/.pico-sdk/cmake/v3.31.5/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:32 (project)"
    message: |
      The target system is: PICO -  - cortex-m33
      The host system is: Windows - 10.0.26100 - AMD64
...
